### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by priceinjector** [rahatarmanahmed/CircularProgressView#12] opened 2015-05-09 12:44 UTC
Hi,
I try to use it with image pager UIL library. 
https://github.com/nostra13/Android-Universal-Image-Loader/tree/master/sample
There is an adapter with item that has an image and a progrees bar on top of it, after the image is loaded the progress bar is hidden. So there are many instances of a progress bar there...

UIL crashes with an error about out of memory on their sample application after about 10-20 swipes.
With a standard progress bar this doesn't happen

**Comment by rahatarmanahmed** [comment] 2015-05-09 16:52
Looking at the live memory graph in Android studio confirms this, I'll have to take a look and figure out what's leaking.

**Comment by rahatarmanahmed** [comment] 2015-05-09 18:46
Wait, never mind, that seems to happen without a CircularProgressView, for whatever reason. I've checked heap dumps of the sample CPV application and there doesn't appear to be anything out of the ordinary.

**Comment by rahatarmanahmed** [comment] 2015-05-09 18:55
Just tried replacing the ProgressBar in ImageGridFragment.java and item_image_grid.xml with a CPV and I don't get any OOM error on my Nexus 5.

**Comment by priceinjector** [comment] 2015-05-09 18:57
Strange, so why replacing it with native progressbar doesn't have the
memory issue? Maybe it is something in CPV params?

**Comment by rahatarmanahmed** [comment] 2015-05-09 18:59
Perhaps, heres the diff of the sample after my changes:

diff --git a/sample/AndroidManifest.xml b/sample/AndroidManifest.xml
index c88a090..d22c8c7 100644
--- a/sample/AndroidManifest.xml
+++ b/sample/AndroidManifest.xml
@@ -5,7 +5,7 @@
     android:versionName="1.9.4" >
 
     <uses-sdk
-        android:minSdkVersion="5"
+        android:minSdkVersion="22"
         android:targetSdkVersion="22" />
 
     <uses-permission android:name="android.permission.INTERNET" />
@@ -14,8 +14,7 @@
     <application
         android:name=".UILApplication"
         android:icon="@drawable/ic_launcher"
-        android:label="@string/app_name"
-		android:allowBackup="false">
+        android:label="@string/app_name">
         <activity
             android:name=".activity.HomeActivity"
             android:label="@string/app_name" >
diff --git a/sample/build.gradle b/sample/build.gradle
index 41190c3..a838e09 100644
--- a/sample/build.gradle
+++ b/sample/build.gradle
@@ -17,6 +17,8 @@ repositories {
 
 dependencies {
     compile fileTree(dir: 'libs', include: '*.jar')
+    compile 'com.github.rahatarmanahmed:circularprogressview:2.2.1'
+
 }
 
 android {
diff --git a/sample/res/layout/item_grid_image.xml b/sample/res/layout/item_grid_image.xml
index 875f936..8051341 100644
--- a/sample/res/layout/item_grid_image.xml
+++ b/sample/res/layout/item_grid_image.xml
@@ -11,12 +11,12 @@
 		android:contentDescription="@string/descr_image"
 		android:scaleType="centerCrop" />
 
-	<ProgressBar
+	<com.github.rahatarmanahmed.cpv.CircularProgressView
+		xmlns:app="http://schemas.android.com/apk/res-auto"
 		android:id="@+id/progress"
 		android:layout_width="match_parent"
 		android:layout_height="wrap_content"
-		android:indeterminate="false"
-		android:max="100"
+		app:cpv_indeterminate="false"
 		android:layout_gravity="bottom"
 		style="@style/ProgressBarStyle" />
 </FrameLayout>
\ No newline at end of file
diff --git a/sample/src/com/nostra13/universalimageloader/sample/fragment/ImageGridFragment.java b/sample/src/com/nostra13/universalimageloader/sample/fragment/ImageGridFragment.java
index d338feb..768f4a8 100644
--- a/sample/src/com/nostra13/universalimageloader/sample/fragment/ImageGridFragment.java
+++ b/sample/src/com/nostra13/universalimageloader/sample/fragment/ImageGridFragment.java
@@ -27,6 +27,8 @@ import android.widget.BaseAdapter;
 import android.widget.GridView;
 import android.widget.ImageView;
 import android.widget.ProgressBar;
+
+import com.github.rahatarmanahmed.cpv.CircularProgressView;
 import com.nostra13.universalimageloader.core.DisplayImageOptions;
 import com.nostra13.universalimageloader.core.ImageLoader;
 import com.nostra13.universalimageloader.core.assist.FailReason;
@@ -102,7 +104,7 @@ public class ImageGridFragment extends AbsListViewBaseFragment {
 				holder = new ViewHolder();
 				assert view != null;
 				holder.imageView = (ImageView) view.findViewById(R.id.image);
-				holder.progressBar = (ProgressBar) view.findViewById(R.id.progress);
+				holder.progressBar = (CircularProgressView) view.findViewById(R.id.progress);
 				view.setTag(holder);
 			} else {
 				holder = (ViewHolder) view.getTag();
@@ -138,6 +140,6 @@ public class ImageGridFragment extends AbsListViewBaseFragment {
 
 	static class ViewHolder {
 		ImageView imageView;
-		ProgressBar progressBar;
+		CircularProgressView progressBar;
 	}
 }
\ No newline at end of file

**Comment by priceinjector** [comment] 2015-05-09 19:00
It is in the image pager sample... but probably it is the same... will
check. Thanks!

**Comment by rahatarmanahmed** [comment] 2015-05-19 01:54
Closing due to no activity.

**Comment by OFmarting** [comment] 2015-05-28 12:58
Hi,
I'm using your library in my application. Recently I integrated squares  new library [LeakCanary](https://github.com/square/leakcanary) which detects memory leaks. I think your library might leak the context. LeakCanary created the following log:

```
D/LeakCanary﹕ * .MainActivity has leaked:
D/LeakCanary﹕ * GC ROOT android.view.Choreographer$FrameDisplayEventReceiver.this$0
D/LeakCanary﹕ * references android.view.Choreographer.mCallbackQueues
D/LeakCanary﹕ * references array android.view.Choreographer$CallbackQueue[].[1]
D/LeakCanary﹕ * references android.view.Choreographer$CallbackQueue.mHead
D/LeakCanary﹕ * references android.view.Choreographer$CallbackRecord.action
D/LeakCanary﹕ * references android.animation.ValueAnimator$AnimationHandler.mAnimations
D/LeakCanary﹕ * references java.util.ArrayList.array
D/LeakCanary﹕ * references array java.lang.Object[].[10]
D/LeakCanary﹕ * references android.animation.ValueAnimator.mUpdateListeners
D/LeakCanary﹕ * references java.util.ArrayList.array
D/LeakCanary﹕ * references array java.lang.Object[].[0]
D/LeakCanary﹕ * references com.github.rahatarmanahmed.cpv.CircularProgressView$5.this$0 (anonymous class implements android.animation.ValueAnimator$AnimatorUpdateListener)
D/LeakCanary﹕ * references com.github.rahatarmanahmed.cpv.CircularProgressView.mContext
D/LeakCanary﹕ * leaks .MainActivity instance
```

To confirm this I also created an empty project with a single activity and a CPV. After rotating the device LeakCanary reported the same memory leak.

**Comment by rahatarmanahmed** [comment] 2015-05-31 19:04
Looks like the ValueAnimators are doing something funky.

Can you share the code for the empty project? Tried using LeakCanary in the example project but it didn't catch anything.

**Comment by priceinjector** [comment] 2015-05-31 19:30
Sorry, I dont have it anymore... it was a simple pager example from UIL
library with your circular progress instead of the native one

**Comment by rahatarmanahmed** [comment] 2015-05-31 19:41
I meant to ask @OFmarting

**Comment by OFmarting** [comment] 2015-06-01 08:50
[Here](https://github.com/OFmarting/CPVTest) is the project.

**Comment by rahatarmanahmed** [comment] 2015-06-05 04:28
Apologies for the delay. Confirmed the memory leak with @OFmarting's test project (Thank you! I think some of the Thread business in the example code prevented LeakCanary from catching the leak.).

It seems as if there are some ValueAnimators that retain a reference to the CPV which contains a reference to the context it was in, after exiting that context. [Added some code](https://github.com/rahatarmanahmed/CircularProgressView/commit/8ea4a9d73edc607cbf42a932bc1811bebfc32b58) to `onDetachedFromWindow()` to ensure that those ValueAnimators are properly cancelled. It seems this stops LeakCanary from finding any memory leaks, but I'm not 100% since LeakCanary doesn't immediately catch the leak so I may have missed the message.

@priceinjector, @OFmarting: Can either of you try to confirm if this commit fixes the memory leak? ([This](http://stackoverflow.com/a/17490233) may help you reference your local clone of CPV instead of the one in the maven repo. I don't want to release a new version until I confirmed the fix.)

**Comment by OFmarting** [comment] 2015-06-05 12:18
Looks good. All occupied memory is reclaimed after a configuration change.
Good job!

**Comment by rahatarmanahmed** [comment] 2015-06-05 18:28
Okay, just released v2.3.1, and the fix is in there.

**Closed by rahatarmanahmed** 2015-06-05 18:28 UTC

**Comment by OFmarting** [comment] 2015-06-09 07:24
I noticed a small issue in the solution. When using the CPV in a ListView or RecyclerView where Views are recycled/reused the CPV stops when it gets visible the second time. The solution is to override  ```onAttachedToWindow()```  and call ```startAnimation()``` there. 

I think you could even move the block

```
if(autostartAnimation)
    startAnimation();
```

from ```init(AttributeSet attrs, int defStyle)``` to ```onAttachedToWindow()```.

Sorry for overlooking that issue.

**Comment by rahatarmanahmed** [comment] 2015-06-09 12:57
Go ahead and make a new issue for it
